#version of the Compose file format
version: '3.8'

services:
  nginx:
    container_name: nginx
    # depends_on:
    #   wordpress:
    #     condition: service_started
    build: ./requirements/nginx
    ports:
      - 443:443 
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - network

  wordpress:
    container_name: wordpress
    # depends_on:
    #   mariadb:
    #     condition: service_healthy
    build: ./requirements/wordpress
      # context: ./requirements/wordpress
      # dockerfile: Dockerfile
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - network
    env_file:
      - .env

  # mariadb:
  #   container_name: mariadb
  #   build: ./requirements/mariadb
  #   # healthcheck:
  #   #   test: ["CMD", "mysqladmin", "ping", "--silent"]
  #   #   start_period: 20s
  #   volumes:
  #     - mariadb_data:/var/lib/mysql
  #   restart: always
  #   networks:
  #     - network
  #   env_file:
  #     - .env

volumes:
  # mariadb_data:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: /home/cwastche/data/mysql
  #     o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/cwastche/data/wordpress
      o: bind

networks:
  network:
    driver: bridge