#WORDPRESS: content management system (CMS) written in PHP that uses a MySQL database. Used to create a website

#Specifies parent img from which we are building
FROM debian:buster

# https://www.digitalocean.com/community/tutorials/how-to-install-wordpress-with-docker-compose